config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :messages
  resources :friendships do
    collection do
      get 'accept'
      get 'show_friend_requests_notification'
    end
  end
  post 'like' => "users#like"
  post 'unlike' => "users#unlike"
  post 'comment' => 'users#comment'
  get 'friend/:id' => 'users#show_friend', as: :friend_profile
  resources :users do
    collection do
      get 'friends'
    end
    resources :posts
  end
  root "home#home"

end

app/views/shared/_chat_window.html.erb
<div class="navbar-fixed-bottom" id='chat-window', style="left:none;">
  <div class="container" style="width: 350px; float: right;">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-primary">
          <div class="panel-heading chat-reciever-user-name">
            <i class="fa fa-comment"></i>
            <span id='message-reciever-name'> </span>
            <div class="btn-group pull-right">
              <button type="button" class="btn btn-default btn-xs dropdown-toggle chat-window-option" data-toggle="dropdown">
                <i class="fa fa-angle-down"></i>
              </button>
              <button type="button" class="btn btn-default btn-xs chat-window-close">
                <i class="fa fa-times"></i>
              </button>
               <!--  <ul class="dropdown-menu slidedown">
                    <li><a href="http://www.jquery2dotnet.com"><span class="glyphicon glyphicon-refresh">
                    </span>Refresh</a></li>
                    <li><a href="http://www.jquery2dotnet.com"><span class="glyphicon glyphicon-ok-sign">
                    </span>Available</a></li>
                    <li><a href="http://www.jquery2dotnet.com"><span class="glyphicon glyphicon-remove">
                    </span>Busy</a></li>
                    <li><a href="http://www.jquery2dotnet.com"><span class="glyphicon glyphicon-time"></span>
                        Away</a></li>
                    <li class="divider"></li>
                    <li><a href="http://www.jquery2dotnet.com"><span class="glyphicon glyphicon-off"></span>
                        Sign Out</a></li>
                </ul> -->
            </div>
          </div>
          <div class="panel-body" style="overflow:auto;">
            <ul class="chat-history"></ul>
            <ul class="chat"></ul>
          </div>

          <%= form_for Message.new, :remote => true do |f| %>
            <div class="panel-footer">
              <div class="input-group">
                <%= f.text_field :content, id: "btn-input", class: "form-control input-sm enter-chat-box", placeholder: "Type your message here...", autocomplete: 'off', required: true %>
                <%= hidden_field_tag 'reciever_id' %>
                <span class="input-group-btn">
                  <%= f.submit "Send", class: "btn btn-warning btn-sm", id: "btn-chat" %>
                </span>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_comment.html.erb
<li class="top-padding-10 white-top-border">
  <div class="row">
  <div class='col-md-12'>
    <div class='col-md-1 padding-none'><%= image_tag comment.user.profile_pic.url(:thumb), class: 'thumb-img' %></div>
    <div class='col-md-10'>
      <span class="blue-color"><strong><%= comment.user.full_name %></strong></span>
      <span><%= comment.message %></span>
      <p class='small text-muted'><i class='fa fa-clock-o'></i> <%= time_ago_in_words(comment.created_at) %> ago</p>
    </div>
  </div>
</div>
</li>

app/views/shared/_feed.html.erb
<% user = feed.user %>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 add-friend item">
    <div class="col-md-12 white-box">
      <div class='row top-space'>
        <div class="col-md-2"> 
          <%=image_tag user.profile_pic.url, height: "50px"%> 
        </div>
        <div class="col-md-10"> 
          <div><b><%=user.full_name%></b></div>
          <span class="font-small">
             <p class='text-muted'><i class='fa fa-clock-o'></i> <%= time_ago_in_words(feed.created_at) %> ago</p>
          </span>
        </div>
      </div>
      <% if feed.message.present? %>
        <div class='row top-space'>
          <div class="col-md-12">
            <%= auto_link(feed.message) %>
          </div>
        </div>
      <% end %>
      <% if feed.image.present? %>
        <div class='row top-space'>
          <div class="col-md-12">
            <%=image_tag feed.image.url, class: 'post-img' %>
          </div>
        </div>
      <% end %>
      <div class='row top-space grey-color'>
        <div class="col-md-6" sytle="background-color:'#ccced3'">
          <span id="like-<%= feed.id %>">
            <% unless current_user.is_like?(feed) %>
              <%=link_to "Like", like_path(type: 'Post', feed_id: feed.id), class: "font-small", remote: true, method: :post %>
            <% else %>
              <%=link_to "Unlike", unlike_path(type: 'Post', feed_id: feed.id), class: "font-small", remote: true, method: :post %>
            <% end %>
          </span>
          <span id="comment-<%= feed.id %>">
            <%=link_to "Comment", "#", class: "font-small"%>
          </span>
          <span id="share-<%= feed.id %>">
            <%=link_to "Share", "#", class: "font-small"%>
          </span>
        </div>
        <div class="col-md-6" sytle="background-color:'#ccced3'">
          <span> <i class="fa fa-thumbs-o-up"></i><span id="like-<%= feed.id %>-count"> <%= feed.likes.count %></span> </span>
        </div>
      </div>

      <!-- Comments -->
    <div class="col-md-12" style="background-color: #F6F7F8;">
      <ul id="comment-<%=feed.id%>-message" class="comment-list">
        <%= render partial: 'shared/comment', collection: feed.comments %>
      </ul>
      <%= form_for(Comment.new, url: comment_path(feed_id: feed.id), remote: true) do |f| %>
        <%= f.text_area :message, class: 'auto-grow fixed_text_area top-space', rows: "3", cols: "54", placeholder: 'What about this post?' %>
        <%= f.submit "Comment", class: 'btn btn-small btn-primary pull-right comment-btn' %>
      <% end %>
    </div>
      <!-- End Comments -->

    </div>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/shared/_feeds.html.erb
<div id="container" class="news_feeds">
  <%= render partial: 'shared/feed', collection: feeds %>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <%= link_to "Connecting People", root_path, class: 'navbar-brand' %>
  </div>
  <!-- Top Menu Items -->
  <ul class="nav navbar-right top-nav">
    <li class="dropdown">
      <%= link_to show_friend_requests_notification_friendships_path, class: "dropdown-toggle notification", "data-toggle"=>"dropdown", id: "friend_requests", remote: true do %>
        <i class="fa fa-users"></i> <b class="caret"></b>
      <% end %>

      <ul class="dropdown-menu message-dropdown notification-box">
          <div class="loader text-center"><i class="fa fa-refresh fa-spin"></i></div>
          <li class="message-footer">
            <%= link_to "All Friend", friendships_path %> 
          </li>
      </ul>
  </li>
  <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
      <ul class="dropdown-menu alert-dropdown">
          <li>
              <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
          </li>
          <li>
              <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
          </li>
          <li>
              <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
          </li>
          <li>
              <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
          </li>
          <li>
              <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
          </li>
          <li>
              <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
          </li>
          <li class="divider"></li>
          <li>
              <a href="#">View All</a>
          </li>
      </ul>
  </li>
  <% if user_signed_in? %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.full_name %> <b class="caret"></b></a>
      <ul class="dropdown-menu">
          <li>
            <%= link_to user_path(current_user) do %>
              <i class="fa fa-fw fa-user"></i> Profile
            <%end%>
          </li>
          <li>
              <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
          </li>
          <li>
              <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-fw fa-power-off"></i> Log Out
            <% end %>
          </li>
      </ul>
    </li>
  <% end %>
</ul>
<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul class="nav navbar-nav side-nav">
    <li class="<%= active_class(root_path) %>">
      <a href="/"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
    </li>
    <li class="<%= active_class(friendships_path) %>">
      <%= link_to friendships_path do %>
        <i class="fa fa-fw fa-user"></i> Friends
      <%end%>
    </li>

    <li>
      <a href="javascript:void(0);" data-toggle="collapse" data-target="#chat-user-list"><i class="fa fa-fw fa-file"></i> Chat<i class="fa fa-fw fa-caret-down"></i></a>
      <ul id="chat-user-list" class="collapse" >
        <% current_user.friends.each do |friend| %>
          <li>
            <%=link_to friend.full_name, "javascript:void(0);", class: "user-for-chat", "data-value"=> friend.id, "data-name" => friend.full_name %>
          </li>
        <% end %>
      </ul>
    </li>
    <li>
  </ul>
</div>


    <!-- /.navbar-collapse -->
</nav>