config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :messages
  resources :friendships do
    collection do
      get 'accept'
      get 'show_friend_requests_notification'
    end
  end
  post 'like' => "users#like"
  post 'unlike' => "users#unlike"
  post 'comment' => 'users#comment'
  get 'friend/:id' => 'users#show_friend', as: :friend_profile
  resources :users do
    collection do
      get 'friends'
    end
    resources :posts
  end
  root "home#home"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  enum status: [ :pending, :accepted, :rejected, :removed ]
  belongs_to :user
  belongs_to :friend, :class_name => 'User'

  scope :pending_requests, -> { where("status = ?",  0 ) }
  scope :accepted_requests, -> { where("status = ?",  1) }

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def index
    @friendships = current_user.friendships.accepted_requests
    @pending_friendships = current_user.friendships.pending_requests
    @friends_request = current_user.inverse_friendships.pending_requests
    @users = User.suggested_friends(current_user)
    @friends = current_user.friends
  end

  def create
    params[:friend_id] = User.find_by(slug: params[:friend_id]).id if params[:friend_id].to_i==0
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id], status: 0)
    if @friendship.save
      flash[:success] = "Friend request has been sent"
      message = render_to_string(partial: 'friendrequest_notification', locals: {sender: current_user, created_at: @friendship.created_at})
      PrivatePub.publish_to("/notification/friend_request-#{@friendship.friend.id}", {message: message, reciever_id: @friendship.friend.id})
      redirect_to friendships_path
    else
      flash[:error] = "Unable to add friend."
      redirect_to friendships_path
    end
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    my_friend_friendship = @friendship.friend.friendships.where(friend_id: current_user.id).last
    my_friend_friendship.update_attributes(status: 3, removed_at: Time.now) if my_friend_friendship

    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to friendships_path
  end

  def accept
    friend_request = User.friendly.find(params[:friend_id])
    request_from = friend_request.friendships.pending_requests.where(friend_id: current_user).last
    if request_from.blank?
      flash[:error] = "Invalid friend request"
      redirect_to friendships_path and return
    end
    request_from.status = 1
    friendship = current_user.friendships.build(:friend_id => request_from.user.id, status: 1)

    if friendship.save and request_from.save
      flash[:message] = "Removed friendship."
      redirect_to friendships_path
    else
      flash[:error] = "Can't create friendship!"
      redirect_to friendships_path
    end
  end

  def show_friend_requests_notification
    @pending_requests = current_user.my_pending_friend_requests.order('created_at desc')
    respond_to do |format|
      format.json
      format.js
    end
  end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_friendrequest_notification.html.erb
<li class='message-preview'>
  <a href='#'>
    <div class='media'>
      <span class='pull-left'>
        <%= image_tag current_user.profile_pic.url(:thumb), class: 'media-object', alt: 'User Image' %>
      </span>
      <div class='media-body'>
        <h5 class='media-heading'><strong><%= sender.full_name %></strong></h5>
        <p class='small text-muted'><i class='fa fa-clock-o'></i> <%= time_ago_in_words(created_at) %> ago</p>
        <p><button class="btn btn-success btn-mini accept" data-url = "/friendships/accept?friend_id=<%=sender.slug%>" >Accept</button></p>
      </div>
    </div>
  </a>
</li>

app/views/friendships/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h3> Your Friends </h3>
  </div>
</div>
<% unless @friendships.blank? %>
  <div class="row box">
      <div class="col-lg-12 box-margin-top">
        <% @friendships.each do |friendship| %>
          <% friend = friendship.friend %>
          <div class="col-md-6 add-friend">
            <div class="col-md-12 box">
              <div class="col-md-4 set-pull-left pic">
                <%= image_tag friend.profile_pic.url(:thumb)%>
              </div>
              <div class="col-md-6">
                <div style="height:45px"></div>
                <strong><%= link_to friend.full_name, friend_profile_path(friend) %></strong>
              </div>
              <div class="col-md-2">
                <div style="height:45px"></div>
                <%= link_to friendship, :method => :delete, class: "btn btn-danger btn-large" do %>
                  <i class="icon-white icon-remove"></i> Unfriend
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>
<% end %>

<% unless @pending_friendships.blank? %>
  <div class="row">
    <div class="col-lg-12">
      <h2> Sent Friend Requests</h2>
    </div>
  </div>
  <div class="row box">
      <div class="col-lg-12 box-margin-top">
        <% @pending_friendships.each do |friendship| %>
          <% friend = friendship.friend %>
          <div class="col-md-6 add-friend">
            <div class="col-md-12 box">
              <div class="col-md-4 set-pull-left pic">
                <%= image_tag friend.profile_pic.url(:thumb)%>
              </div>
              <div class="col-md-5">
                <div style="height:45px"></div>
                <strong><%= link_to friend.full_name, "javascript:void(0)" %></strong>
              </div>
              <div class="col-md-3">
                <div style="height:45px"></div>
                <%= link_to friendship, :method => :delete, class: "btn btn-primary btn-large" do %>
                  <i class="icon-white icon-remove"></i> Cancel Request</a>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>
<% end %>

<% unless @friends_request.blank? %>
  <div class="row">
    <div class="col-lg-12">
      <h2> Receive Friends Request</h2>
    </div>
  </div>
  <div class="row box">
      <div class="col-lg-12 box-margin-top">
        <% @friends_request.each do |fr| %>
          <% user = fr.user %>
          <div class="col-md-6 add-friend">
            <div class="col-md-12 box">
              <div class="col-md-4 set-pull-left pic">
                <%= image_tag user.profile_pic.url(:thumb) %>
              </div>
              <div class="col-md-5">
                <div style="height:45px"></div>
                <strong><%= link_to user.full_name, "javascript:void(0)" %></strong>
              </div>
              <div class="col-md-3">
                <div style="height:45px"></div>
                <%= link_to accept_friendships_path(:friend_id => user), class: "btn btn-primary btn-large" do %>
                  <i class="icon-white icon-remove"></i> Accept
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>
<% end %>  

<% unless @users.blank? %>
  <div class="row">
    <div class="col-lg-12">
      <h4> Suggested Friends </h4>
    </div>
  </div>
  <div class="row box">
      <div class="col-lg-12 box-margin-top">
        <% @users.each do |user| %>
          <div class="col-md-6 add-friend">
            <div class="col-md-12 box">
              <div class="col-md-4 set-pull-left pic">
                <%= image_tag user.profile_pic.url(:thumb)%>
              </div>
              <div class="col-md-5">
                <div style="height:45px"></div>
                <strong><%= link_to user.full_name, "javascript:void(0);" %></strong>
              </div>
              <div class="col-md-3">
                <div style="height:45px"></div>
                <%= link_to friendships_path(:friend_id => user), :method => :post, class: "btn btn-primary btn-large" do %>
                  <i class="icon-white icon-remove"></i> Add Friend
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>
<% end %>

app/views/friendships/show_friend_requests_notification.js.erb
<% @pending_requests.each do |pending_request| %>
  var html = "<%= escape_javascript(render(:partial=> 'friendrequest_notification', :locals => {:sender=> pending_request.user,
  :created_at => pending_request.created_at, :add_class => 'ajax_noti'})) %>";
  $(".notification-box").prepend(html);
<% end %>

$(".loader").hide();